extend schema for console and error log
basho/riak pull request #902
Opened 2017-03-13 17:57 UTC by joecaswell

make console and error log size, rotation, and keep configurable in riak.conf

urrently these are hardcoded in the schema. Advanced.config requires
specifying a full handlers block that includes all settings for all log
files in order to modify them.
Add 6 configuration points:
log.console.size
log.console.rotation
log.console.rotation.keep
log.error.size
log.error.rotation
log.error.rotation.keep

2017-03-30 19:15 UTC, angrycub requested changes

2017-03-30 19:15 UTC, angrycub commented on rel/files/riak.schema
> +{mapping, "log.error.rotation.keep", "lager.crash_log_count", [
should this be mapped to crash_log_count?

2017-04-03 06:22 UTC, joecaswell commented
Absolutely correct, that should have been mapped to lager.handlers.  The way it was, if it were the only setting specified, it may be been ignored.  The tests passed because the translation functions pull the settings by the riak.conf name, not their mapped name.

2017-04-03 14:12 UTC, angrycub approved these changes

2017-04-03 15:23 UTC, bsparrow435 commented
+1

2019-06-14 08:46 UTC, closed without merging